# Generated by Django 4.2.4 on 2023-09-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('category', models.CharField(max_length=100)),
                ('tags', models.JSONField(default=list)),
            ],
        ),
    ]
