# Generated by Django 4.2.4 on 2023-09-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_category_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('vent', 'Vent'), ('poems', 'Poems'), ('convo', 'Convo')], default='', max_length=50),
        ),
    ]
